version: "3.8"
services:
  frontend:
    tty: true
    image: front_end_image
    container_name: front_end_container
    environment:
    - WATCHPACK_POLLING=true
    volumes:
    - ./garage_front_end/src/:/garage_front_end/src/
    - ./garage_front_end/public/:/garage_front_end/public/
    ports:
      - "3000:3000"
  
  backend:
    tty: true
    image: back_end_image
    container_name: back_end_container
    environment:
      - "DISPLAY=${DISPLAY}"
      - "QT_X11_NO_MITSHM=1"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./garage_back_end/:/garage_back_end/
      - /garage_back_end/projects/simulator/build
    ports:
      - "4000:4000"
    command: ["bash", "/garage_back_end/installation_scripts/run_back_end.sh"]   