# Generated by Django 4.2.11 on 2024-11-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation',
            old_name='steps',
            new_name='message',
        ),
    ]
