# Generated by Django 4.2.11 on 2024-11-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_app', '0002_rename_steps_simulation_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation',
            old_name='message',
            new_name='simulation_steps',
        ),
    ]
